
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: local-postgres
  namespace: default
spec:
  hosts:
  - host.minikube.internal
  location: MESH_EXTERNAL
  ports:
  - number: 5432
    name: tcp-postgres
    protocol: TCP
  resolution: DNS
